# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
# test now the role has been modified
name: AWS example workflow
on:
  push:
    branches:
      - 'test'
env:
  BUCKET_NAME : "gccc-misp-sandbox-tfstate"
  AWS_REGION : "eu-west-2"
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
        with:
          ref: dev-single-script
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::891377055542:role/GithubActionsRole
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}
      # list AWS s3
      - name:  terraform apply
        run: |
          terraform init
          terraform apply
